### ISSUE TITLE
Mod files are distributed with signature files so no one can load own build

### ISSUE THREAD

**Issue by eLEcTRiCZiTy** [m00nl1ght-dev/MapPreview#9]
Hi,

I wanted to remix (for my own use) your Map Preview mod to include option to get and set map seeds directly but I can't. Your framework verifies every file with its signature (a lfc file). You did not provide any info or tool to generate signatures.

You released this mod as "free to remix", so please make it this way!

**Comment by m00nl1ght-dev** [comment]
The lfc files are just MD5 checksums, not signatures. The purpose is to verify the integrity of the mod files, nothing more.

The reason for why I'm doing that is described here:
https://github.com/m00nl1ght-dev/MapPreview/blob/main/1.4/Lunar/README.md

And the tool to generate them is included in the repository of the framework:
https://github.com/m00nl1ght-dev/LunarFramework/tree/master/Sources/LunarDevTools

To use it, clone that repository, build the project and load the LunarDevTools assembly into the game like any other.
On startup, it will automatically generate/update the checksum files if there are changes.

**Comment by m00nl1ght-dev** [comment]
If you don't want to build it yourself, I've now also added a pre-built assembly packaged as a mini-mod, for convenient loading:
https://github.com/m00nl1ght-dev/LunarFramework/releases/tag/1.1.2

**Comment by eLEcTRiCZiTy** [comment]
> The reason for why I'm doing that is described here: https://github.com/m00nl1ght-dev/MapPreview/blob/main/1.4/Lunar/README.md

Ah, sorry. I only looked for the README in the root directory and totally missed this one.

Thanks for the explanation. Now I understand how LunarDevTools works and that I also need to consider framework sources. This topic can be great for others who want to work with your mods and get lost.

btw.. It is not only MD5 -- you XORed the version too as I see in sources :) At first, I tried MD5 because these files have only 16 bytes but it did not match.

**Comment by m00nl1ght-dev** [comment]
> btw.. It is not only MD5 -- you XORed the version too as I see in sources :) At first, I tried MD5 because these files have only 16 bytes but it did not match.

Ah right, I included the version because otherwise old files would still pass validation after e.g. an incomplete update.
